### ISSUE TITLE
Split samples and template from releases versions

### ISSUE THREAD

**Issue by HaraldWalker** [ardas/stripo-plugin#11]
Trying to download the samples requires downloading the full repository and with all the released versions in the master branch, that means that > 650MB have to be downloaded (download failed after 650MB, so I do not know how much it really is). 

Better to move the samples and templates into a separate git repo.

**Comment by antongrinenko** [comment]
Hi,

Separate git repo with samples was created: 
https://github.com/ardas/stripo-plugin-samples/

**Comment by HaraldWalker** [comment]
Thank you Anton for the super fast response.
