### ISSUE TITLE
css conflict with latest bootstrap (4.4.1)

### ISSUE THREAD

**Issue by luposky** [ardas/stripo-plugin#3]
Hi, 

simply adding the latest boostrap css (just the css, not the js files) in the head section of your example (https://github.com/ardas/stripo-plugin/tree/master/Samples/client-side-code-sample) broke the stripo layout ... any workaround?

![image](https://user-images.githubusercontent.com/1070180/70356510-d9f1d900-1874-11ea-9ec6-20db498fd926.png)

best regards,
Luca

**Comment by antongrinenko** [comment]
Hi,
Stripo ships with bootstrap v3.3.7.
If you want to use latest bootstrap you can load Stripo editor in iframe.
See https://github.com/ardas/stripo-plugin/tree/master/Samples/iframe-client-side-code-sample
