### ISSUE TITLE
Buttons remove spaces from links

### ISSUE THREAD

**Issue by chris-bonadonna-mixpanel** [ardas/stripo-plugin#4]
We use the stripo plugin in conjunction with templating, such that our users can add links with pieces that should be substituted out, for example:
`http:// google.com/{{my subdomain}}`
For button links, and as far as I can tell only buttons, the spaces get removed when we move on to the next page, such that the above would become:
`http://google.com/{{mysubdomain}}`
this then fails the templating when we pass it to the backend because the variable we're trying to substitute doesn't exist. Is this something that could be fixed? Or would it constitute too significant of a change in behavior?

**Comment by DKulaksyz** [comment]
Hello @chris-bonadonna-mixpanel 
Thanks a lot for this issue. We've prepared the task to fix this in the release of the 1.19.0 version expected in early March.

**Comment by chris-bonadonna-mixpanel** [comment]
Great, thanks for the update!

**Comment by DKulaksyz** [comment]
Hello @chris-bonadonna-mixpanel
The fix for this issue has been included to the 1.18.0 version of plugin released last week. Please clarify how it works?

**Comment by chris-bonadonna-mixpanel** [comment]
Great, thank you! We've integrated the new version and confirmed that it works.
